# Generated by Django 3.2.5 on 2021-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=250, unique=True)),
                ('entity', models.JSONField(default=tuple)),
            ],
        ),
    ]
