# Generated by Django 3.2.5 on 2021-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=None, upload_to='pdf_collection'),
        ),
    ]
