# Generated by Django 3.2.5 on 2021-07-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_entity', '0003_alter_pdf_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file_name',
            field=models.TextField(unique=True),
        ),
    ]
